# Generated by Django 5.0.1 on 2024-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_course_photo_courseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo_next',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.DeleteModel(
            name='CourseImage',
        ),
    ]
