# Generated by Django 5.0.1 on 2024-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_course_photo_course_photo_next_delete_courseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
