# Generated by Django 5.0.1 on 2024-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='heads/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Head',
                'verbose_name_plural': 'Company Heads',
            },
        ),
    ]
