# Generated by Django 5.0.1 on 2024-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_instructor_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
