# Generated by Django 5.0.1 on 2024-01-13 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='days',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
